reference: "hg38"
fasta: /projects/standard/hsiehph/shared/hsiehph_shared/assemblies/hg38/no_alt/fastcn/hg38.no_alt_umasked.fa
sd: /projects/standard/hsiehph/shared/hsiehph_shared/assemblies/hg38/no_alt/fastcn/hg38.no_alt_SDs_plus_lowid_SDs.bed
nchunks: 100
manifest: /projects/standard/hsiehph/gordo893/pipelines/fastcn/mitchells_github_hg38/config/manifest.tbl
