reference: "t2t-chr22_only"
fasta: /panfs/jay/groups/7/hsiehph/gordo893/pipelines/fastcn/tiny_dataset/chr22.fa
sd: /panfs/jay/groups/7/hsiehph/gordo893/pipelines/fastcn/tiny_dataset/chm13_v2.0.SD_only_chr22.bed
nchunks: 100
manifest: config/manifest.tbl

#
# the following files will be made if they are not provided
#
