name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.0.0
      - uses: actions-rs/toolchain@v1
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: build application
        run: make
      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1.22.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "--use-conda --cores 6 --configfile .test/config.yaml"
